obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.381, 0.1524], [-0.381, 0.1524], [-0.381, -0.1524], [0.381, -0.1524]]
inflation_radius: 0.55

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: lidar, data_type: PointCloud, topic: point_cloud, marking: true, clearing: true}
