standalone_tags:
  [

    {id: 0, size: 0.194},
    {id: 1, size: 0.194},
    {id: 2, size: 0.194},
    {id: 3, size: 0.194},
    {id: 4, size: 0.194},
    {id: 5, size: 0.194},
    {id: 6, size: 0.194},
    {id: 7, size: 0.194},
    {id: 8, size: 0.194},
    {id: 9, size: 0.194},
    {id: 10, size: 0.194},
    {id: 11, size: 0.194},
    {id: 12, size: 0.194},
    {id: 13, size: 0.194},
    {id: 14, size: 0.194},
    {id: 15, size: 0.194},
  ]
tag_bundles:
  [
    {
      name: 'sieve-marker',
      layout:
        [
          {id: 3, size: 0.19, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 8, size: 0.19, x: 0.2178, y: -0.2227, z: 0.0037, qw: 0.9999, qx: -0.0133, qy: 0.0047, qz: -0.0008},
          {id: 4, size: 0.19, x: 0.2175, y: -0.0002, z: 0.0030, qw: 0.9999, qx: -0.0100, qy: 0.0076, qz: 0.0003},
          {id: 7, size: 0.19, x: -0.0009, y: -0.2228, z: 0.0008, qw: 0.9998, qx: -0.0158, qy: 0.0075, qz: -0.0006}
        ]
    }
  ]
