standalone_tags:
  [
    {id: 8, size: 0.1985},
    {id: 9, size: 0.1985},
    {id: 10, size: 0.1985},
    {id: 11, size: 0.1985},
    {id: 12, size: 0.1985},
    {id: 13, size: 0.1985},
    {id: 14, size: 0.1985},
    {id: 15, size: 0.1985},
  ]
tag_bundles:
  []

