map_topic: "maps/costmap_node/global_costmap/costmap"
odom_topic: "/rtabmap/odom"
goal_topic: "/goal"
path_topic: "global_path"
pc_topic: "point_cloud"
cmd_vel_topic: "/cmd_vel"
occ_threshold: 128 # corresponds to possibly-in-collision
