map_topic: "maps/costmap_node/global_costmap/costmap"
odom_topic: "odom"
goal_topic: "goal"
path_topic: "global_path"
pc_topic: "point_cloud"
cmd_vel_topic: "cmd_vel"
excavation_topic: "/excavation"
deposition_topic: "/deposition"
drivetrain_topic: "/drivetrain"
actuation_topic: "/actuation"

occ_threshold: 128 # corresponds to possibly-in-collision