plugins: 
  - {name: static,  type: "costmap_2d::StaticLayer"} 
  - {name: inflation,  type: "costmap_2d::InflationLayer"} 
  - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
publish_frequency: 10.0
global_frame: "odom"
robot_base_frame: "base_link"
footprint: "[ [0.54615446154,0.295590],[0.546154,-0.295590],[-0.546154,-0.295590],[-0.546154,0.295590] ]"
map_topic: "/rtabmap/octomap_grid"
width: 20.0
height: 20.0

inflation: 
  inflation_radius: 0.3,
  cost_scaling_factor: 4

obstacles: 
    observation_sources: "d455_front d455_back"
    d455_front: {data_type: "PointCloud2", 
      sensor_frame: "d455_front_link", 
      clearing: true, 
      marking: true, 
      topic: "/d455_front/clouds",
      obstacle_min_range: 0.1,
      min_obstacle_height: -9999.0,
      max_obstacle_height: 9999.0
    }
    d455_back: {data_type: "PointCloud2",
      sensor_frame: "d455_back_link", 
      clearing: true, 
      marking: true, 
      topic: "/d455_back/clouds",
      obstacle_min_range: 0.1,
      min_obstacle_height: -9999.0,
      max_obstacle_height: 9999.0
    }
    combination_method: 2
    
