rollout_count: 50
top_rollouts: 15
iterations: 10
w_linear: 1.0
w_angular: 5.0
w_waypoint: 20.0
w_occupied: 0.0
horizon_length: 10
frequency: 30
min_distance_threshold: 0.5
velocity_limits:
  linear: [-0.3, 0.3]
  angular: [-1.5, 1.5]
