odom_topic: "/rtabmap/odom"
cmd_vel_topic: "/cmd_vel"
nav_goal_topic: "/goal"
nav:
    map_topic: "/maps/costmap_node/global_costmap/costmap"
    global_path_topic: "/nav/global_path"
    occ_threshold: 80 # corresponds to possibly-in-collision
    num_lerp_pts: 10
    num_bezier_pts: 5
    dstar_node:
      hz: 5
      robot_grid_radius: 8 # grid units
