depth_topics:
  - /d435_backward/depth/color/points
  - /d435_forward/depth/color/points
depth_frame_id: "d435_backward_link"
pc_topic: "/point_cloud"
odom_topic: "/odom"
nav_goal_topic: "/goal"
cmd_vel_topic: "/cmd_vel"

nav:
    map_topic: "/maps/costmap_node/global_costmap/costmap"
    global_path_topic: "/nav/global_path"
    occ_threshold: 80 # corresponds to possibly-in-collision
    bezier_step: 0.01
    lerp_step: 0.05
