name: Re-usable Docker Build

env:
  REPO_NAME: purduelunabotics/2022-2023

on:
  workflow_call:
    inputs:
      tag:
        default: "latest"
        required: false
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      - name: Build and push (tag)
        if: inputs.tag != 'latest'
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REPO_NAME }}:${{ inputs.tag }}
          cache-from: type=registry,ref=${{ env.REPO_NAME }}:cache
          push: true
          context: ./docker
      - name: Build and push (latest)
        if: inputs.tag == 'latest'
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REPO_NAME }}
          cache-from: type=registry,ref=${{ env.REPO_NAME }}:cache
          cache-to: type=registry,ref=${{ env.REPO_NAME }}:cache,mode=max
          push: true
          context: ./docker
